// Created by iWeb 3.0 local-build-20130108

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWStrokeParts([{rect:new IWRect(-2,2,4,250),url:'Cara_Leigh_files/stroke.png'},{rect:new IWRect(-2,-2,4,4),url:'Cara_Leigh_files/stroke_1.png'},{rect:new IWRect(2,-2,300,4),url:'Cara_Leigh_files/stroke_2.png'},{rect:new IWRect(302,-2,5,4),url:'Cara_Leigh_files/stroke_3.png'},{rect:new IWRect(302,2,5,250),url:'Cara_Leigh_files/stroke_4.png'},{rect:new IWRect(302,252,5,4),url:'Cara_Leigh_files/stroke_5.png'},{rect:new IWRect(2,252,300,4),url:'Cara_Leigh_files/stroke_6.png'},{rect:new IWRect(-2,252,4,4),url:'Cara_Leigh_files/stroke_7.png'}],new IWSize(304,254)),shadow_0:new IWShadow({blurRadius:6,offset:new IWPoint(-0.8998,3.8975),color:'#000000',opacity:0.750000}),shadow_1:new IWShadow({blurRadius:6,offset:new IWPoint(0.4875,3.9702),color:'#000000',opacity:0.750000})});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Cara_Leigh_files/Cara_LeighMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');adjustLineHeightIfTooBig('id10');adjustFontSizeIfTooBig('id10');detectBrowser();adjustLineHeightIfTooBig('id11');adjustFontSizeIfTooBig('id11');adjustLineHeightIfTooBig('id12');adjustFontSizeIfTooBig('id12');adjustLineHeightIfTooBig('id13');adjustFontSizeIfTooBig('id13');adjustLineHeightIfTooBig('id14');adjustFontSizeIfTooBig('id14');adjustLineHeightIfTooBig('id15');adjustFontSizeIfTooBig('id15');fixAllIEPNGs('Media/transparent.gif');fixupIECSS3Opacity('id3');IMpreload('Cara_Leigh_files','shapeimage_3','0');IMpreload('Cara_Leigh_files','shapeimage_4','0');IMpreload('Cara_Leigh_files','shapeimage_5','0');Widget.onload();fixupAllIEPNGBGs();applyEffects()}
function onPageUnload()
{Widget.onunload();}
