// Created by iWeb 3.0 local-build-20130213

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWStrokeParts([{rect:new IWRect(-1,1,2,1158),url:'Cara_Leigh_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'Cara_Leigh_files/stroke_1.png'},{rect:new IWRect(1,-1,1544,2),url:'Cara_Leigh_files/stroke_2.png'},{rect:new IWRect(1545,-1,2,2),url:'Cara_Leigh_files/stroke_3.png'},{rect:new IWRect(1545,1,2,1158),url:'Cara_Leigh_files/stroke_4.png'},{rect:new IWRect(1545,1159,2,2),url:'Cara_Leigh_files/stroke_5.png'},{rect:new IWRect(1,1159,1544,2),url:'Cara_Leigh_files/stroke_6.png'},{rect:new IWRect(-1,1159,2,2),url:'Cara_Leigh_files/stroke_7.png'}],new IWSize(1546,1160)),shadow_1:new IWShadow({blurRadius:6,offset:new IWPoint(0.4875,3.9702),color:'#000000',opacity:0.750000}),stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,273),url:'Cara_Leigh_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'Cara_Leigh_files/stroke_9.png'},{rect:new IWRect(1,-1,327,2),url:'Cara_Leigh_files/stroke_10.png'},{rect:new IWRect(328,-1,2,2),url:'Cara_Leigh_files/stroke_11.png'},{rect:new IWRect(328,1,2,273),url:'Cara_Leigh_files/stroke_12.png'},{rect:new IWRect(328,274,2,2),url:'Cara_Leigh_files/stroke_13.png'},{rect:new IWRect(1,274,327,2),url:'Cara_Leigh_files/stroke_14.png'},{rect:new IWRect(-1,274,2,2),url:'Cara_Leigh_files/stroke_15.png'}],new IWSize(329,275)),shadow_0:new IWShadow({blurRadius:6,offset:new IWPoint(-0.8998,3.8975),color:'#000000',opacity:0.750000})});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Cara_Leigh_files/Cara_LeighMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');adjustLineHeightIfTooBig('id10');adjustFontSizeIfTooBig('id10');detectBrowser();adjustLineHeightIfTooBig('id11');adjustFontSizeIfTooBig('id11');adjustLineHeightIfTooBig('id12');adjustFontSizeIfTooBig('id12');fixAllIEPNGs('Media/transparent.gif');fixupIECSS3Opacity('id3');IMpreload('Cara_Leigh_files','shapeimage_4','0');IMpreload('Cara_Leigh_files','shapeimage_5','0');IMpreload('Cara_Leigh_files','shapeimage_6','0');Widget.onload();fixupAllIEPNGBGs();applyEffects()}
function onPageUnload()
{Widget.onunload();}
